security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_chain_provider:
            chain:
                providers: [ app_student_provider, app_teacher_provider ]
        app_student_provider:
            entity:
                class: App\Domain\Entity\Student
                property: login
        app_teacher_provider:
            entity:
                class: App\Domain\Entity\Teacher
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        token:
            pattern: ^/api/v1/get-token
            security: false
        register:
            pattern: ^/api/v1/register
            security: false
        main:
            lazy: true
            stateless: true
            provider: app_chain_provider
            custom_authenticator: App\Application\Security\ApiTokenAuthenticator

    role_hierarchy:
        ROLE_ADMIN: # Полный доступ ко всем функциям
            - ROLE_STUDENT # Просмотр своих данных, поиск группы
            - ROLE_TEACHER # Управление группами, подбор преподавателей
            - ROLE_VIEW
            - ROLE_GET_LIST
        ROLE_TEACHER: [ ROLE_USER ] # ROLE_USER - Базовая роль для всех аутентифицированных
        ROLE_STUDENT: [ ROLE_USER ] # ROLE_USER - Базовая роль для всех аутентифицированных

    access_control:
        - { path: /api/v1/group, roles: [ ROLE_ADMIN ], methods: [ POST ] }
        - { path: /api/v1/groups, roles: [ ROLE_ADMIN, ROLE_STUDENT, ROLE_TEACHER ], methods: [ GET ] }
        - { path: /api/v1/group, roles: [ ROLE_ADMIN, ROLE_STUDENT, ROLE_TEACHER ], methods: [ GET ] }
        - { path: ^/api/v1/group, roles: [ ROLE_ADMIN ], methods: [ DELETE ] }
        - { path: /api/v1/student, roles: [ ROLE_ADMIN, ROLE_STUDENT ], methods: [ POST ] }
        - { path: /api/v1/students, roles: [ ROLE_ADMIN, ROLE_STUDENT ], methods: [ GET ] }
        - { path: /api/v1/student, roles: [ ROLE_ADMIN, ROLE_STUDENT ], methods: [ GET ] }
        - { path: ^/api/v1/student, roles: [ ROLE_ADMIN ], methods: [ DELETE ] }
        - { path: /api/v1/teacher, roles: [ ROLE_ADMIN, ROLE_TEACHER ], methods: [ POST ] }
        - { path: /api/v1/teachers, roles: [ ROLE_ADMIN, ROLE_TEACHER ], methods: [ GET ] }
        - { path: /api/v1/teacher, roles: [ ROLE_ADMIN, ROLE_TEACHER ], methods: [ GET ] }
        - { path: ^/api/v1/teacher, roles: [ ROLE_ADMIN ], methods: [ DELETE ] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon