<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250611185535 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE "group" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, teacher_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6DC044C541807E1D ON "group" (teacher_id)');
        $this->addSql('CREATE TABLE group_skills (group_id BIGINT NOT NULL, skill_id BIGINT NOT NULL, PRIMARY KEY(group_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_6B7CEA0FE54D947 ON group_skills (group_id)');
        $this->addSql('CREATE INDEX IDX_6B7CEA05585C142 ON group_skills (skill_id)');
        $this->addSql('CREATE TABLE skill (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE student (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, login VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, group_id BIGINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B723AF33FE54D947 ON student (group_id)');
        $this->addSql('CREATE TABLE student_skill (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, priority INT DEFAULT 1 NOT NULL, student_id BIGINT NOT NULL, skill_id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D60A9DEACB944F1A ON student_skill (student_id)');
        $this->addSql('CREATE INDEX IDX_D60A9DEA5585C142 ON student_skill (skill_id)');
        $this->addSql('CREATE TABLE teacher (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, login VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE teacher_skill (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, teacher_id BIGINT NOT NULL, skill_id BIGINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FC2582A41807E1D ON teacher_skill (teacher_id)');
        $this->addSql('CREATE INDEX IDX_FC2582A5585C142 ON teacher_skill (skill_id)');
        $this->addSql('ALTER TABLE "group" ADD CONSTRAINT FK_6DC044C541807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_skills ADD CONSTRAINT FK_6B7CEA0FE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE group_skills ADD CONSTRAINT FK_6B7CEA05585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33FE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_skill ADD CONSTRAINT FK_D60A9DEACB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_skill ADD CONSTRAINT FK_D60A9DEA5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_skill ADD CONSTRAINT FK_FC2582A41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE teacher_skill ADD CONSTRAINT FK_FC2582A5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "group" DROP CONSTRAINT FK_6DC044C541807E1D');
        $this->addSql('ALTER TABLE group_skills DROP CONSTRAINT FK_6B7CEA0FE54D947');
        $this->addSql('ALTER TABLE group_skills DROP CONSTRAINT FK_6B7CEA05585C142');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33FE54D947');
        $this->addSql('ALTER TABLE student_skill DROP CONSTRAINT FK_D60A9DEACB944F1A');
        $this->addSql('ALTER TABLE student_skill DROP CONSTRAINT FK_D60A9DEA5585C142');
        $this->addSql('ALTER TABLE teacher_skill DROP CONSTRAINT FK_FC2582A41807E1D');
        $this->addSql('ALTER TABLE teacher_skill DROP CONSTRAINT FK_FC2582A5585C142');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE group_skills');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE student_skill');
        $this->addSql('DROP TABLE teacher');
        $this->addSql('DROP TABLE teacher_skill');
    }
}